openapi: 3.1.0
info:
  title: RandomCoffee
  version: 0.1.0

tags:
  - name: communities
  - name: meet
  - name: user

paths:
  /communities:
    get:
      tags:
        - communities
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommunitiesList'

  /communities/find:
    get:
      tags:
        - communities
      parameters:
        - name: search by name
          in: query
          description: Text to filter by
          required: false
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CommunitiesList'

components:
  schemas:
    Community:
      type: object
      properties: 
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        userCount:
          type: integer
          format: int64
        isOpen:
          type: boolean
    CommunitiesList:
      type: array
      items:
        $ref: '#/components/schemas/Community'
